### ISSUE TITLE
Bindings using RoadNetwork unique_ptr are not working.

### ISSUE THREAD

**Issue by francocipollone** [maliput/delphyne#846]
### Summary
`maliput_py` stopped relying on custom pybind11 version. This seems to be causing a failure in `delphyne` bindings that are using `std::unique_ptr<RoadNetwork>`

https://github.com/maliput/delphyne/blob/141bc619447546c429591e45211ec7c2f38633a9/python/delphyne/roads.cc#L86-L90

Here `delphyne::roads::CreateMalidriveRoadNetworkFromXodr` returns a `std::unique_ptr<RoadNetwork>`. When using this binding this it is throwing an error because:
```
     File "/__w/delphyne_demos/delphyne_demos/maliput_ws/install/delphyne/lib/python3.8/site-packages/delphyne/behaviours/roads.py", line 146, in setup
        delphyne.roads.create_malidrive_road_network_from_xodr(
    TypeError: Unable to convert function return value to a Python type! The signature was
    	(name: str, file_path: str, rule_registry_file_path: str, road_rulebook_file_path: str, traffic_light_book_path: str, phase_ring_path: str, intersection_book_path: str, linear_tolerance: float = 0.001, angular_tolerance: float = 0.001) -> maliput::api::RoadNetwork
```

When `maliput_py`'s bindings are compiled using the custom `pybind11` version it works correctly. 

#### Related
https://github.com/maliput/maliput_infrastructure/issues/225

**Comment by agalbachicar** [comment]
Some ideas:
- Move the delphyne python api that depends on maliput to not use maliput python bindings.
- Build a service like API in delphyne to interact with maliput. Agents would make calls to the service instead of maliput pointers directly.

**Comment by francocipollone** [comment]
> Some ideas:
> 
> * Move the delphyne python api that depends on maliput to not use maliput python bindings.
> * Build a service like API in delphyne to interact with maliput. Agents would make calls to the service instead of maliput pointers directly.

I like the idea and I think that for how things are right now it's the tidier option.
What I found a bit bittersweet is that because of just using `unique_ptr` on already binded maliput type we can't rely directly on the maliput_py bindings which, not only is what they are for, but also delphyne could be seen as an example for the community on how using the bindings.

I have a workaround in this [branch](https://github.com/maliput/delphyne/commit/a15cc3076d444715c17d200105092a7e16fc6721) for this. 
We could drop a real nice docstring explaining there, and once we move to Jammy, (technically we would be able to deal with this particular case), we could remove this.

Wdyt?

**Comment by agalbachicar** [comment]
I concur. Note my comment in https://github.com/maliput/delphyne/commit/a15cc3076d444715c17d200105092a7e16fc6721#r77070044 which I guess it should help to reduce the code maintenance in delphyne for this workaround.

 The second part of the comment might not be as useful because of use cases though.
